# This file will be included by the Makefile under the project directory.

FLOAT_O := $(FLOAT:.a=.o)
FLOAT_VFPRINTF_O := $(dir $(FLOAT))FLOAT_vfprintf.o

FLOAT_CFLAGS_EXTRA := -O2 -m32 -fno-builtin

FLOAT_A_OBJ := $(FLOAT_O) $(FLOAT_VFPRINTF_O)

$(FLOAT): $(FLOAT_A_OBJ)
	ar r $@ $^

# TODO: complete the following rules

$(FLOAT_O): lib-common/FLOAT.c
	mkdir -p obj/lib-common
	$(CC) $(FLOAT_CFLAGS_EXTRA) -o $(FLOAT_O) -c lib-common/FLOAT.c -Ilib-common

$(FLOAT_VFPRINTF_O):

